### ISSUE TITLE
Support edge labels

### ISSUE THREAD

**Issue by bugeats** [glejeune/node-graphviz#24]
```
digraph G {
    a -> b [label="a to b"];
    b -> c [label="another label"];
}
```

**Comment by glejeune** [comment]
```
var e = g.addEdge(n1, n2);
e.set("label", "hello world");
```

**Comment by sneko** [comment]
I don't know why but it's actually not working on my side.

EDIT: I switched to https://github.com/ts-graphviz/ts-graphviz , labels work great and no longer "false output success" when there is something wrong not generating the graph. Still, thanks for you work!
