### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by wbinnssmith** [glejeune/node-graphviz#32]
The license field in the package.json says this module is licensed under the GPL v3 but there's an MIT LICENSE file in the root of the repo.

Can you clarify the license of this module and update one or the other location?

Thanks!

P.S. It would be wonderful if this were licensed as MIT :)

**Comment by glejeune** [comment]
You right it's MIT, there is an error in the package.json...

**Comment by larshp** [comment]
https://www.npmjs.com/package/graphviz still lists "GPL"

suggest publishing a new patch or updating
